name: Backend-build

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

defaults:
  run:
    working-directory: ./backend

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Clean install
      run: |
        npm ci

    - name: Build
      run: npm start
    
    - name: Tests
      run: npm run test
