name: Backend-build

on:
  push:
    paths:
      - backend/**
  pull_request:
    paths:
      - backend/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x, 25.x, 26.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean install
      working-directory: ./backend
      run: |
        npm ci

    - name: Build
      working-directory: ./backend
      run: npm start --if-present
    
    - name: Tests
      working-directory: ./backend
      run: npm run test
